#[cfg(test)]
mod tests {
    #[test]
    fn constitutional_boundaries_are_explicit() {
        let rules = [
            "ACCESS != AUTHORIZATION",
            "DECISION != AUTHORITY",
            "DECISION != EXECUTION",
            "AUTHORITY != AUTHORIZATION",
            "AUTHORIZATION != EXECUTION",
            "AUTHORIZATION REQUIRED FOR EXECUTION",
            "EXECUTION PERMIT REQUIRED",
            "SIGNATURE != AUTHORITY",
            "PROVENANCE != PERMISSION",
            "UNKNOWN => FAIL_CLOSED",
            "QUESTION != EVIDENCE",
            "EVIDENCE != EPISTEMIC_STATE",
            "THRESHOLD != DECISION",
            "EXECUTION RECEIPT != EXECUTION PERMIT",
            "OBSERVATION != EXECUTION",
            "EXECUTION SUCCESS REQUIRES OBSERVATION",
            "UNKNOWN EXECUTION OUTCOME => FAIL_CLOSED",
            "CONSEQUENCE != OBSERVATION",
            "REASSESSMENT REQUIRES NEW HISTORY",
            "REVOCATION => STOP",
            "EXPIRATION => STOP",
            "SUSPENSION => REASSESS",
            "ACTIVE AUTHORITY => LIFECYCLE MAY CONTINUE",
            "REVOKE => PROPAGATE",
            "REVOCATION PRESERVES PROVENANCE",
            "REVOCATION DOES NOT REWRITE HISTORY",
            "PROPAGATION STATUS IS EXPLICIT",
            "AUTHORIZATION BINDS AUTHORITY IDENTITY",
            "MISMATCHED AUTHORITY => STOP",
            "REVOCATION PERSISTS THROUGH EVENTSTORE",
            "REVOCATION EVENT IS IMMUTABLE",
            "COMET PRESERVES REVOCATION IDENTITY",
            "AUTHORITY REVOCATION => AUTHORIZATION INVALIDATION",
            "INVALIDATED AUTHORIZATION => EXECUTION STOP",
            "COMET REQUIRES AUTHORITY IDENTITY MATCH",
            "INACTIVE AUTHORIZATION => NO NEW EXECUTION PERMIT",
            "AUTHORIZATION INVALIDATION => IMMUTABLE EVENT",
            "AUTHORIZATION INVALIDATION PRESERVES REVOCATION IDENTITY",
            "AUTHORIZATION INVALIDATION => PERSISTENT RECONSTRUCTION",
        ];

        assert_eq!(rules.len(), 38);
    }
}
