(function(){
'use strict';
var KEY='palaco-cx001';var state={identity:null,docs:[],current:null,template:'blank'};
function $(s,r){return (r||document).querySelector(s)}function $$(s,r){return Array.from((r||document).querySelectorAll(s))}
function now(){return new Date().toISOString()}function id(p){return p+'-'+crypto.randomUUID()}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function hash(v){var b=new TextEncoder().encode(JSON.stringify(v));var h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
function load(){try{var raw=localStorage.getItem(KEY);if(raw){var x=JSON.parse(raw);state.identity=x.identity||null;state.docs=x.docs||[]}}catch(e){}state.current=state.docs.slice().sort(function(a,b){return b.updatedAt.localeCompare(a.updatedAt)})[0]||newDoc();renderIdentity();renderDoc()}
function persist(){localStorage.setItem(KEY,JSON.stringify({identity:state.identity,docs:state.docs}))}
function templateBlocks(t){if(t==='citadel')return[{id:id('BLK'),type:'heading',text:'Citadel overview',at:now()},{id:id('BLK'),type:'text',text:'Purpose, context and boundaries of this Citadel.',at:now()},{id:id('BLK'),type:'provenance',at:now()}];if(t==='proof')return[{id:id('BLK'),type:'heading',text:'Evidence note',at:now()},{id:id('BLK'),type:'text',text:'Describe the observation. Keep claim, source and verification state separate.',at:now()},{id:id('BLK'),type:'provenance',at:now()}];return[]}
function newDoc(){return{id:id('DOC'),title:'Untitled document',purpose:'',citadel:'',visibility:'PRIVATE',template:state.template,status:'LOCAL_DRAFT',verification:'UNVERIFIED',authority:'NONE',creatorId:state.identity?state.identity.palacoId:null,revision:0,createdAt:now(),updatedAt:now(),blocks:templateBlocks(state.template)}}
function go(v){$$('.view').forEach(function(n){n.classList.toggle('visible',n.dataset.panel===v)});$$('.rail button').forEach(function(n){n.classList.toggle('active',n.dataset.view===v)});if(v==='docs')renderLibrary();if(v==='proof')renderProof();if(v==='build')renderDoc();$('#main').focus({preventScroll:true})}
async function saveIdentity(form){var f=new FormData(form),base=state.identity||{palacoId:'PALACO-ID-'+crypto.randomUUID(),createdAt:now(),version:'CX-001/0.1'};state.identity={palacoId:base.palacoId,createdAt:base.createdAt,version:base.version,name:(f.get('name')||'').trim()||'Unnamed creator',alias:(f.get('alias')||'').trim(),purpose:(f.get('purpose')||'').trim(),status:'LOCAL_DRAFT',verification:'UNVERIFIED',authority:'NONE',updatedAt:now()};state.identity.digest=await hash(state.identity);if(state.current&&!state.current.creatorId)state.current.creatorId=state.identity.palacoId;persist();renderIdentity();renderDoc()}
function renderIdentity(){var c=$('#identity-card'),f=$('#identity-form');if(!state.identity){c.innerHTML='<p class="eyebrow">PALACO · IDENTITY</p><h3>No local ID yet</h3><p>Create one to bind local documents to a visible creator reference.</p>';f.reset();return}f.elements.name.value=state.identity.name||'';f.elements.alias.value=state.identity.alias||'';f.elements.purpose.value=state.identity.purpose||'';c.innerHTML='<p class="eyebrow">PALACO · IDENTITY</p><h3>'+esc(state.identity.name)+'</h3><p>'+esc(state.identity.purpose||'Local creator identity')+'</p><dl><dt>ID</dt><dd>'+esc(state.identity.palacoId)+'</dd><dt>Alias</dt><dd>'+esc(state.identity.alias||'—')+'</dd><dt>Status</dt><dd>LOCAL DRAFT</dd><dt>Verification</dt><dd>UNVERIFIED</dd><dt>Authority</dt><dd>NONE</dd><dt>Digest</dt><dd>'+esc(state.identity.digest||'—')+'</dd></dl>'}
function sync(){if(!state.current)return;state.current.title=$('#title').value.trim()||'Untitled document';state.current.purpose=$('#purpose').value.trim();state.current.citadel=$('#citadel').value.trim();state.current.visibility=$('#visibility').value}
async function saveDoc(){sync();state.current.creatorId=state.identity?state.identity.palacoId:state.current.creatorId;state.current.revision+=1;state.current.updatedAt=now();var copy=JSON.parse(JSON.stringify(state.current));delete copy.digest;state.current.digest=await hash(copy);var i=state.docs.findIndex(function(d){return d.id===state.current.id});if(i<0)state.docs.push(JSON.parse(JSON.stringify(state.current)));else state.docs[i]=JSON.parse(JSON.stringify(state.current));persist();renderDoc();renderLibrary()}
function addBlock(t){if(t==='image'){$('#image-dialog').showModal();return}var b={id:id('BLK'),type:t,at:now()};if(t==='heading')b.text='New heading';if(t==='text')b.text='Write here…';state.current.blocks.push(b);$('#doc-state').textContent='UNSAVED · REV '+state.current.revision;renderDoc()}
function fileAsDataUrl(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result)};r.onerror=function(){reject(r.error)};r.readAsDataURL(file)})}
async function insertImage(){var input=$('#image-file'),file=input.files&&input.files[0];if(!file){input.setCustomValidity('Choose an image first.');input.reportValidity();return}if(file.size>1500000){input.setCustomValidity('Use an image smaller than 1.5 MB in CX-001.');input.reportValidity();return}input.setCustomValidity('');var data=await fileAsDataUrl(file);state.current.blocks.push({id:id('BLK'),type:'image',data:data,name:file.name,role:$('#image-role').value,caption:$('#image-caption').value.trim(),source:$('#image-source').value.trim(),verification:'UNVERIFIED',at:now()});$('#image-form').reset();$('#image-dialog').close();renderDoc()}
function controls(b){return '<div class="block-actions"><button data-block="up" data-id="'+b.id+'">↑</button><button data-block="down" data-id="'+b.id+'">↓</button><button data-block="delete" data-id="'+b.id+'">×</button></div>'}
function renderDoc(){if(!state.current)state.current=newDoc();$('#title').value=state.current.title;$('#purpose').value=state.current.purpose||'';$('#citadel').value=state.current.citadel||'';$('#visibility').value=state.current.visibility||'PRIVATE';$('#sheet-owner').textContent=state.identity?state.identity.name:(state.current.creatorId||'NO ID');$('#sheet-id').textContent=state.current.id;$('#creator').textContent=state.current.creatorId||(state.identity?state.identity.palacoId:'NO ID');$('#digest').textContent=state.current.digest?state.current.digest.slice(0,24)+'…':'NOT SEALED';$('#doc-state').textContent=(state.current.revision?'SAVED LOCAL':'UNSAVED')+' · REV '+state.current.revision;var box=$('#blocks');if(!state.current.blocks.length){box.innerHTML='<div class="empty"><p class="eyebrow">BLANK TEMPLATE</p><p>Add a heading, text, image, provenance card or divider.</p></div>';return}box.innerHTML=state.current.blocks.map(function(b){var inner='';if(b.type==='heading')inner='<input class="heading-input" data-edit="'+b.id+'" value="'+esc(b.text||'')+'">';if(b.type==='text')inner='<textarea class="text-input" data-edit="'+b.id+'">'+esc(b.text||'')+'</textarea>';if(b.type==='divider')inner='<div class="divider"></div>';if(b.type==='provenance')inner='<div class="prov"><div><span class="eyebrow">CREATOR</span><b>'+esc(state.current.creatorId||(state.identity?state.identity.palacoId:'NO ID'))+'</b></div><div><span class="eyebrow">STATUS</span><b>LOCAL DRAFT</b></div><div><span class="eyebrow">VERIFICATION</span><b>UNVERIFIED</b></div><div><span class="eyebrow">CITADEL</span><b>'+esc(state.current.citadel||'—')+'</b></div></div>';if(b.type==='image')inner='<figure><img src="'+b.data+'" alt="'+esc(b.caption||b.role)+'"><figcaption><span>'+esc(b.caption||b.name)+'</span><span class="role">'+esc(b.role)+'</span></figcaption><p class="boundary">Source: '+esc(b.source||'not supplied')+' · UNVERIFIED</p></figure>';return '<section class="block '+(b.type==='image'?'image-block':'')+'" data-block-id="'+b.id+'">'+inner+controls(b)+'</section>'}).join('')}
function move(idv,a){var i=state.current.blocks.findIndex(function(b){return b.id===idv});if(i<0)return;if(a==='delete')state.current.blocks.splice(i,1);if(a==='up'&&i>0){var x=state.current.blocks[i-1];state.current.blocks[i-1]=state.current.blocks[i];state.current.blocks[i]=x}if(a==='down'&&i<state.current.blocks.length-1){var y=state.current.blocks[i+1];state.current.blocks[i+1]=state.current.blocks[i];state.current.blocks[i]=y}renderDoc()}
function renderLibrary(){var t=$('#library');if(!state.docs.length){t.innerHTML='<article class="panel"><h3>No saved documents yet</h3><p>Build your first document and save a revision.</p></article>';return}t.innerHTML=state.docs.slice().sort(function(a,b){return b.updatedAt.localeCompare(a.updatedAt)}).map(function(d){return '<article class="card"><p class="eyebrow">'+esc(d.template)+' · REV '+d.revision+'</p><h3>'+esc(d.title)+'</h3><p>'+esc(d.purpose||'No purpose supplied.')+'</p><p class="boundary">'+esc(d.id)+' · '+esc(d.visibility)+' · UNVERIFIED</p><div class="row"><button data-open="'+d.id+'">Open</button><button data-delete="'+d.id+'">Delete</button></div></article>'}).join('')}
async function renderProof(){var p=$('#proof-id');p.innerHTML=state.identity?'<p><b>'+esc(state.identity.name)+'</b></p><p>'+esc(state.identity.palacoId)+'</p><p>LOCAL DRAFT · UNVERIFIED · AUTHORITY NONE</p><code>'+esc(state.identity.digest)+'</code>':'<p>No local identity.</p>';var c=JSON.parse(JSON.stringify(state.current));delete c.digest;var d=await hash(c);$('#proof-doc').innerHTML='<p><b>'+esc(state.current.title)+'</b></p><p>'+esc(state.current.id)+' · REV '+state.current.revision+'</p><p>LOCAL DRAFT · UNVERIFIED · AUTHORITY NONE</p><code>'+d+'</code>'}
async function exportDoc(){sync();var payload={schema:'PALACO-CX-001/0.1',exportedAt:now(),boundary:'LOCAL EXPORT — NOT VERIFIED — NO AUTHORITY',identity:state.identity,document:state.current};payload.exportDigest=await hash(payload);var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=(state.current.title||'palaco-document').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.palaco.json';a.click();setTimeout(function(){URL.revokeObjectURL(u)},1000)}
function rio(q){q=q.toLowerCase();if(q.includes('image')||q.includes('foto')||q.includes('citadel'))return 'Build → Image. Choose the file, then select Citadel image, Cover, Illustration, Source / evidence, or Watermark reference. The role is metadata only; it never verifies the image.';if(q.includes('id'))return 'Open ID. Create a local creator reference. It remains LOCAL DRAFT, UNVERIFIED and AUTHORITY NONE.';if(q.includes('provenance')||q.includes('proof'))return 'PALACO keeps creator, source, status, Citadel reference, revision and digest visible. Local hashing detects change but does not establish trust or authority.';if(q.includes('export')||q.includes('save'))return 'Save stores a local revision in this browser. Export creates a .palaco.json package with a SHA-256 export digest.';return 'I can guide identity, building, images, provenance, saving and export. Live RIO intelligence is not connected in CX-001.'}
function rioMsg(who,text){var a=document.createElement('article');a.className=who==='YOU'?'rio-user':'rio-system';a.innerHTML='<b>'+who+'</b><p>'+esc(text)+'</p>';$('#rio-log').appendChild(a);a.scrollIntoView({block:'end'})}
function action(a){if(a==='save')saveDoc();if(a==='export')exportDoc();if(a==='print')window.print();if(a==='new'){sync();state.current=newDoc();renderDoc();go('build')}if(a==='delete-id'){if(confirm('Delete the local PALACO ID?')){state.identity=null;persist();renderIdentity();renderDoc()}}}
document.addEventListener('click',function(e){var n=e.target.closest('[data-goto]');if(n){go(n.dataset.goto);return}n=e.target.closest('[data-view]');if(n){go(n.dataset.view);return}n=e.target.closest('[data-template]');if(n){state.template=n.dataset.template;$$('[data-template]').forEach(function(b){b.classList.toggle('selected',b.dataset.template===state.template)});if(state.current.revision===0&&state.current.blocks.length===0){state.current=newDoc();renderDoc()}else if(confirm('Start a new document from this template?')){state.current=newDoc();renderDoc()}return}n=e.target.closest('[data-add]');if(n){addBlock(n.dataset.add);return}n=e.target.closest('[data-action]');if(n&&n.dataset.action!=='insert-image'){action(n.dataset.action);return}n=e.target.closest('[data-block]');if(n){move(n.dataset.id,n.dataset.block);return}n=e.target.closest('[data-open]');if(n){state.current=JSON.parse(JSON.stringify(state.docs.find(function(d){return d.id===n.dataset.open})));go('build');return}n=e.target.closest('[data-delete]');if(n){if(confirm('Delete this local document?')){state.docs=state.docs.filter(function(d){return d.id!==n.dataset.delete});persist();renderLibrary()}return}n=e.target.closest('[data-rio]');if(n){rioMsg('YOU',n.dataset.rio);rioMsg('RIO',rio(n.dataset.rio))}});
document.addEventListener('input',function(e){var n=e.target.closest('[data-edit]');if(n){var b=state.current.blocks.find(function(x){return x.id===n.dataset.edit});if(b)b.text=n.value;$('#doc-state').textContent='UNSAVED · REV '+state.current.revision}});
$('#identity-form').addEventListener('submit',function(e){e.preventDefault();saveIdentity(e.currentTarget)});
$('#image-form').addEventListener('click',function(e){if(e.target.dataset.action==='insert-image'){e.preventDefault();insertImage()}});
$('#rio-form').addEventListener('submit',function(e){e.preventDefault();var i=$('#rio-input'),q=i.value.trim();if(!q)return;rioMsg('YOU',q);rioMsg('RIO',rio(q));i.value=''});
['title','purpose','citadel'].forEach(function(x){$('#'+x).addEventListener('input',function(){sync();$('#doc-state').textContent='UNSAVED · REV '+state.current.revision})});$('#visibility').addEventListener('change',sync);
load();
})();